# People {-#people}

This project would not be possible without dedicated collaborators.

## Project Coordinator {-}

### Ilythia Morley {-#im}

[Ilythia Morley](https://blogs.ubc.ca/imorley/) is a recent MSc graduate in environmental science. Her research focused on the application of planetary-scale satellite data for predictive ecology and habitat suitability modelling. Ilythia will act as the project coordinator for this project to facilitate communication, data transfers, and product testing.

## Project Leads {-}

### Prof. Nicholas Coops {-#ncc}

[Professor Nicholas Coops](https://forestry.ubc.ca/faculty-profile/nicholas-coops/) holds a Canada Research Chair in Remote Sensing (Tier 1) at UBC. He has published >460 total referenced peer-reviewed journal publications and is internationally recognised as a scientific leader in the field of remote sensing. He was the principal investigator of the AWARE project a 5-year research project focused on developing LIDAR applications in Canada for forestry applications. He is a co-author on the Canadian Forest Service LIDAR best practice guide series, the most downloaded CFS information handbook ever, focused on LIDAR data processing. In 2020, he was the co-receipt of the Marcus Wallenberg prize for scientific achievements contributing to significantly broadening knowledge and technical development within the field of Forestry.

#### Responsibilities {-#responsibilties-ncc}

Coops as the PI will manage the budget, and overall assignment of students and researchers to the project. A postdoctoral fellow (PDF) will be based and supervised by Coops at UBC. They will be co-supervised by Achim at Laval whose team is already developing some approaches for road extraction. At the completion of the project the PDF at UBC will work with Achim’s team at Laval and ensure the software is able to be released openly and publicly to allow other forest management areas in Ontario covered by SPL data to be applied.


### Prof. Alexis Achim {-#aa}

[Professor Alexis Achim](https://www.sbf.ulaval.ca/alexis-achim) is the Director of Laval University’s Renewable Materials Research Centre. He has developed expertise in the field of wood resource assessment and participated in AWARE, a Canada-wide project on using ALS to predict wood fibre resource attributes. The R package ‘lidR’, which is extensively used in the ALS international research community, was developed in his lab as part of the work done for this project. He is currently lead investigator of a new 5 year, $CAD 5million research project (Silva21) developing new silvicultural approaches and technologies for the Canadian Forest industries. 

#### Responsibilities {-#responsibilties-aa}

Achim will help supervise the research undergoing at Laval relevant to roads, to ensure compatibility of approaches and that any insights are available to this project

## Team Members {-#team}

### Jean-Romain Roussel {-#jrr}

[Jean-Romain Roussel](https://github.com/Jean-Romain)

### Prof. Jeff Dech {-#jd}

[Professor Jeff Dech](https://www.nipissingu.ca/users/jeff-dech) is chair of the Department of Biology and Chemistry at Nipissing University. He previously held an Industrial Research Chair in Forest Bioproducts supported by Tembec, and was a co-investigator on the AWARE project. He has developed a research program focused on the use of site classification and stand structure data derived from remote sensing to describe and predict forest growth and quality over broad spatial scales. This work has focused on Ecological Land Classification and LiDAR-derived predictors and has involved the establishment of extensive networks of field plots and intensive sampling campaigns as part of several collaborative projects in the boreal and Great-Lakes St. Lawrence forests. He has extensive field experience in ecological land classification (soil and vegetation surveys), dendrochronological sampling and forest mensuration.

#### Responsibilities {-#responsibilties-jd}

Dech at Nipissing will recruit a Masters student for the field work verification of the project. This student will develop a research program to both sample existing roads and their attributes, compile GIS information to help assess road position and age, as well as develop and then implement a field program to verify road detection produced by the algorithm. This information from the Masters student will be fed back to the PDF at UBC to improve algorithm development.


### Dr. Douglas Reid {-#dr}

[Douglas E.B. Reid](http://www.infogo.gov.on.ca/infogo/home.html#empProfile/27211/en) is the Boreal Silviculture Research Program Lead at the Centre for Northern Forest Ecosystem Research in Thunder Bay. His research has developed tools to evaluate the accuracy of remote sensing approaches to silviculture monitoring and is developing tools to evaluate stand height as a measure of growth performance in regenerating stands using single photon LiDAR. He has knowledge of the importance of roads and their extreme variability from conducting previous work examining caribou habitat conditions within managed and unmanaged forests in Ontario. 

#### Responsibilities {-#responsibilties-dr}

Working with Reid at the Center for Northern Forest Ecosystem Research we will be able to examine the accuracy of the SPL derived road networks with existing approaches such as those from optical remote sensing. His understanding of the importance of roads attributes and age on habitat conditions will provide focus in terms of the relevance of the predicted attributes to cumulative effects mapping. In addition by having government partners on the project ensures that the outcomes will have immediate uptake by other users within the Ministry thereby ensuring successful technology transfer and knowledge exchange. 


### Grant McCartney {-#gmcc}

[Mr. Grant McCartney](https://www.linkedin.com/in/grantmccartneygis) is an analyst at [Forsite](https://www.forsite.ca/), and formally acted as a spatial analyst and forest information systems coordinator with Rayonier Advanced Materials (RYAM) Forest Management. He performs spatial analysis in support of forest management planning (FMP) and forestry operations on the Gordon Cosens, Romeo Malette and Martel – Magpie Forests in Northeastern Ontario, Canada. He leads the acquisition of remotely sensed data including Digital Aerial Photogrammetry (DAP) and LiDAR for RYAM. Grant is a member of the Forest Information Data Advisory Group (FIDAG) and Provincial Forest Inventory Advisory Committee (PFIAC) MNRF committees working to improve the quality of spatial forest information in the province. Grant  has been an industrial partner in numerous research efforts including: the Assessment of Wood Attributes for REmote sensing (AWARE) project, CWFC – FIP, past FFT - KKTD projects and the recently approved Silva 21.

#### Responsibilities {-#responsibilties-gmcc}

There are a number of forest management areas already acquired with SPL data available that will form the initial focus sites. McCartney will provide road vector information and any road construction date and positional information available over their tenure. McCartney or designate will attend project meetings, assess road network accuracy with Ryam staff and test developed software as required. 


### Scott McPherson {-#sm}

Scott McPherson is the planning forester and analyst for the Nipissing and Sudbury Forests of central Ontario, reporting to Nipissing Forest Resource Management, Inc. and the Vermilion Forest Management Company, Ltd. Scott has worked in the government and industry sectors for 25 years, focusing on growth & Yield, silviculture, and planning.


#### Responsibilities {-#responsibilties-sm}

Scott’s current responsibilities include inventory development, strategic planning and modeling, monitoring, and reporting. The newly acquired single photon LiDAR will be a significant asset and Scott is excited about the value it will add to future inventories for forest and road conditions across the land base.
