# Project Overview {-#projoverview}

## Themes {-#themes}

The project is broken down into three themes.

### Theme 1 {-#theme1}

At the focus sites which are known to have poor road network information, either positionally or have significant amounts of unmapped roads, a new PDF will update the current road coverage layers by designing and applying a new algorithm to detect roads in the SPL point cloud and move existing road segments to their accurate position. Currently Coops and Achim have been working with Dr JR Roussel (PDF at Laval University) an expert in LIDAR data processing, on a new algorithm to detect road segments in LIDAR point clouds, which has now been developed and run with success over LiDAR coverages in Quebec. We will further develop and calibrate this new open source algorithm to the SPL point cloud data available in Ontario, and apply it at sites, using the existing road network as a base. We will move the road segments into their correct position using the algorithm, and assess the accuracy using field acquired road segment data collected by a MSc student (Nipissing).

### Theme 2 {-#theme2}

Develop an automated methodology to extract SPL point cloud information on, and surrounding each road segment, to build models of road condition typical of roads in the Canadian boreal forest including attributes such as width, roughness, curvature, biomass on, and adjacent to, the road, and canopy cover above the road. We aim to categorize road conditions, assess the operational status of roads, and pinpoint the thresholds at which decommissioned roads become indistinguishable from surrounding forest cover. A primary outcome from this theme will be research using a test site in Ontario to demonstrate the application of the automated road detection method and SPL derived metrics to determine thresholds of road conditions and indicate the operational status of roads. Outcomes of this research will support road management by identifying road segments that require maintenance and improving our understanding of the interaction between road conditions and forest systems.

### Theme 3 {-#theme3}

We will develop an automated methodology to improve temporal updates. Using freely available Landsat imagery from 1984 – present, we will drill backwards through the SPL derived road segments, to examine changes in spectral values at road locations and assess annual presence. By assessing the date of road establishment we can provide an accumulation layer of road development (and conversely deactivation) for species such as Caribou.


## Methodology {-#methods}

### Road mapping {-#mapping}

We will Develop and apply an automated methodology to improve map accuracy. At focus sites which are known to have poor road network information, either positionally or have significant amounts of unmapped roads, a new PDF will update the current road coverage layers by designing a new algorithm to detect roads in the SPL point cloud and move existing road segments to their accurate position. The PDF will utilise new tools developed at Laval which have been applied with success in parts of Quebec. We will further develop and calibrate this new open source algorithm to the SPL data available in Ontario, and apply it at sites, using the existing road network as a base. We will move the road segments into their correct position and assess the accuracy using field acquired data collected by the MSc student who will review existing and develop as needed new, road condition sampling protocols to characterize road condition with respect to physical form, and surrounding vegetation and conduct field work for a sample of roads for comparison with the SPL predictions. Once the road network has been corrected, we will extend the road network coverage by applying the algorithm to find unmapped roads adjacent to the detected road network. This will ensure the algorithm is robust to false positives and while we acknowledge that is will not be possible to locate and find a full “unmapped” road network, it will be particularly important to avoid mapping false roads. To do so the algorithm will work with geometrical properties of the SPL point cloud taking advantage of the fact that very few natural features are analogous to a road, in geometrical terms (e.g. width, surface roughness). 

### Road attributes {-#attributes}

We will develop an automated methodology to extract SPL point cloud information on, and surrounding each road segment, to build models of road condition attributes. We will also use citizen science tools already developed and tested at UBC which can collect information on traffic speed and road conditions automatically on a cell phone. A key focus of interest in wetter areas will be to identify locations where water crossings have been removed, or modified, associated with the road installation or de-activation, using additional stream information derived from the SPL DEM, given the importance of hydrological restoration when deactivating roads. We will use the field data to train a machine-learning algorithm to predict these attributes along each road segment to inform on the current status and management of the road network. 

### Road timeline {-#timeline}

Using annual Landsat land cover classifications from 1984 – present, we will examine changes in spectral values at road locations. Given road locations are accurately known from steps 1 and 2, any changes in spectral values such as increases or decreases in greenness will likely indicate the road was either established or potentially decommissioned around that year. By assessing the date of road establishment we can provide an accumulation layer of road development (and conversely deactivation) for cumulative effects modelling.